# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckType',
            fields=[
                ('type_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_count', models.IntegerField()),
                ('check_staff', models.IntegerField()),
                ('uncheck_staff', models.IntegerField()),
                ('late_staff', models.IntegerField()),
                ('leave_staff', models.IntegerField()),
                ('daily_text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, verbose_name='部门名称')),
                ('charge', models.CharField(max_length=20, verbose_name='部门主管')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('staff_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[(0, '男'), (1, '女')], max_length=4)),
                ('true_name', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('staff_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='设置项')),
                ('value', models.IntegerField(default=0, verbose_name='参数')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('content', models.CharField(max_length=720)),
                ('url', models.URLField()),
                ('reply_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff')),
            ],
            options={
                'verbose_name_plural': '新闻',
                'verbose_name': '新闻',
            },
        ),
        migrations.CreateModel(
            name='TimeSetting',
            fields=[
                ('setting', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='设置项')),
                ('value', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=50, verbose_name='用户类型')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.UserType'),
        ),
        migrations.AddField(
            model_name='reply',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Theme'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff'),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff'),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.CheckType'),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept'),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff'),
        ),
    ]
