# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(default='', upload_to='reply_img/')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='Theme_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(default='', upload_to='new_img/')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Theme')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[(1, '女'), (0, '男')], max_length=4),
        ),
    ]
