# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0003_auto_20171225_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[(0, '男'), (1, '女')], max_length=4),
        ),
        migrations.AlterField(
            model_name='timesetting',
            name='value',
            field=models.TimeField(),
        ),
    ]
