# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-25 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0004_auto_20171225_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=4),
        ),
    ]
