# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0005_auto_20171225_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(default='', upload_to='notice_img/')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Notice')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='theme_img',
            name='img_url',
            field=models.ImageField(default='', upload_to='theme_img/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='pub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff'),
        ),
    ]
