# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0007_auto_20171230_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinfo',
            options={'verbose_name': '考勤信息', 'verbose_name_plural': '考勤信息'},
        ),
        migrations.AlterModelOptions(
            name='checktype',
            options={'verbose_name': '考勤类型', 'verbose_name_plural': '考勤类型'},
        ),
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name': '日志', 'verbose_name_plural': '日志'},
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': '假条', 'verbose_name_plural': '假条'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='notice_img',
            options={'verbose_name': '公告图片', 'verbose_name_plural': '公告图片'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AlterModelOptions(
            name='reply_img',
            options={'verbose_name': '回复图片', 'verbose_name_plural': '回复图片'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': '系统设置', 'verbose_name_plural': '系统设置'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
        migrations.AlterModelOptions(
            name='theme_img',
            options={'verbose_name': '主题图片', 'verbose_name_plural': '主题图片'},
        ),
        migrations.AlterModelOptions(
            name='timesetting',
            options={'verbose_name': '时间设置', 'verbose_name_plural': '时间设置'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': '用户类型', 'verbose_name_plural': '用户类型'},
        ),
        migrations.AddField(
            model_name='staff',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='考勤时间'),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.CheckType', verbose_name='考勤类型'),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept', verbose_name='部门ID'),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='remarks',
            field=models.CharField(max_length=25, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='checktype',
            name='type_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='check_staff',
            field=models.IntegerField(verbose_name='考勤员工数'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日志创建时间'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='daily_text',
            field=models.TextField(verbose_name='日志文本'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='late_staff',
            field=models.IntegerField(verbose_name='迟到员工数'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='leave_staff',
            field=models.IntegerField(verbose_name='早退员工数'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='staff_count',
            field=models.IntegerField(verbose_name='员工数'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='uncheck_staff',
            field=models.IntegerField(verbose_name='未考勤员工数'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=50, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='staff_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept', verbose_name='员工部门'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='公告时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_text',
            field=models.TextField(verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff', verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Theme', verbose_name='回复主题'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff', verbose_name='回复用户'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=25, null=True, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_no',
            field=models.CharField(max_length=20, null=True, verbose_name='员工号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tel',
            field=models.CharField(max_length=25, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='true_name',
            field=models.CharField(max_length=25, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.UserType', verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.CharField(max_length=720, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后回复时间'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff', verbose_name='发布用户'),
        ),
        migrations.AlterField(
            model_name='timesetting',
            name='value',
            field=models.TimeField(verbose_name='设置时间'),
        ),
    ]
