# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0008_auto_20180106_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nickname',
            field=models.CharField(default='snow', max_length=20, verbose_name='昵称'),
        ),
    ]
