# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0009_auto_20180106_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
    ]
