# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-07 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0011_auto_20180107_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.IntegerField(default=0, max_length=2, verbose_name='登录状态'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], max_length=20, verbose_name='性别'),
        ),
    ]
