# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('winter_sakura', '0013_auto_20180107_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session', verbose_name='已登录session'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], max_length=20, verbose_name='性别'),
        ),
    ]
