# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0014_auto_20180107_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='session',
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=20, verbose_name='性别'),
        ),
    ]
