# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-07 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0015_auto_20180107_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
        migrations.AddField(
            model_name='staff',
            name='active_session',
            field=models.CharField(max_length=50, null=True, verbose_name='登录session'),
        ),
    ]
