# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0018_auto_20180111_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktype',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checktype',
            name='type_name',
            field=models.CharField(max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], max_length=20, verbose_name='性别'),
        ),
    ]
