# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-10 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0020_auto_20180111_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='考勤时间')),
                ('remarks', models.CharField(max_length=25, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name_plural': '考勤信息',
                'verbose_name': '考勤信息',
            },
        ),
        migrations.CreateModel(
            name='CheckType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '考勤类型',
                'verbose_name': '考勤类型',
            },
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.CheckType', verbose_name='考勤类型'),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Dept', verbose_name='部门ID'),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.Staff', verbose_name='员工ID'),
        ),
    ]
