# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0022_leave_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='生成时间'),
            preserve_default=False,
        ),
    ]
