# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0023_leave_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='staff_no',
            field=models.CharField(max_length=20, null=True, verbose_name='员工号'),
        ),
    ]
