# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0024_leave_staff_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='check_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winter_sakura.CheckInfo', verbose_name='考勤号'),
        ),
    ]
