# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-13 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0025_leave_check_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='staff_dept',
        ),
    ]
