# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-14 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_sakura', '0028_auto_20180114_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='日志创建时间'),
        ),
    ]
